-- ═══════════════════════════════════════════════════════════════════════════
-- AffiliateOS Search Engine v6 — three intent layers + richer qualification
--
-- The old keyword pool burned out after ~a month: 1729 of 1985 finds were
-- already-known domains. This replaces the pool wholesale and moves keywords out
-- of code into a table, so their yield can be measured and dead ones retired
-- automatically instead of silently dragging the pipeline down.
--
-- Idempotent: safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Search provenance + qualification fields on leads ──────────────────────
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS search_layer   TEXT;     -- A|B|C
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS source_keyword TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS source_page    INTEGER;

ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS audience_owner        BOOLEAN;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS monetization_signal   BOOLEAN;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS monetization_evidence TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS has_partnership_path  BOOLEAN;

CREATE INDEX IF NOT EXISTS leads_search_layer_idx ON public.leads (search_layer);

-- ── Keyword pool with per-key yield tracking ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.keywords (
  id            BIGSERIAL PRIMARY KEY,
  preset        TEXT NOT NULL,
  layer         TEXT NOT NULL,              -- A = player intent, B = publisher, C = competitor footprint
  keyword       TEXT NOT NULL,
  lang          TEXT,
  active        BOOLEAN DEFAULT TRUE,
  archived_at   TIMESTAMPTZ,
  runs          INTEGER DEFAULT 0,
  urls_found    INTEGER DEFAULT 0,
  leads_created INTEGER DEFAULT 0,
  hot_leads     INTEGER DEFAULT 0,          -- fit_score >= 70
  last_run_at   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE (preset, keyword)
);
CREATE INDEX IF NOT EXISTS keywords_active ON public.keywords (preset, layer) WHERE active = TRUE;

ALTER TABLE public.keywords DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.keywords TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.keywords_id_seq TO anon, authenticated;


-- ── Archive the burned-out v5 pool (kept for provenance, revisit in 3-4 months) ──
INSERT INTO public.keywords (preset, layer, keyword, active, archived_at)
SELECT v.preset, v.layer, v.keyword, FALSE, now()
FROM (VALUES
  ('1xb-ng','A','opay betting nigeria'),
  ('1xb-ng','A','how to cash out bet naija'),
  ('1xb-ng','A','naira betting bonus'),
  ('1xb-ng','A','super eagles betting preview'),
  ('1xb-ng','A','moniepoint betting deposit'),
  ('1xb-ng','A','aviator cash out trick nigeria'),
  ('1xb-ng','A','npfl betting odds'),
  ('1xb-ng','A','palmpay betting site'),
  ('1xb-ng','A','weekend accumulator naija'),
  ('1xb-ng','A','how to withdraw betting winnings nigeria'),
  ('1xb-ke','A','mpesa deposit betting kenya'),
  ('1xb-ke','A','harambee stars betting'),
  ('1xb-ke','A','how to win aviator kenya'),
  ('1xb-ke','A','kplc betting jackpot'),
  ('1xb-ke','A','mpesa withdrawal betting'),
  ('1xb-ke','A','kenya premier league odds'),
  ('1xb-ke','A','safaricom betting deposit'),
  ('1xb-ke','A','midweek jackpot prediction'),
  ('1xb-ke','A','aviator cash out kenya'),
  ('1xb-ke','A','betting bonus kenya today'),
  ('1xb-gh','A','mtn momo betting ghana'),
  ('1xb-gh','A','black stars betting preview'),
  ('1xb-gh','A','how to win aviator ghana'),
  ('1xb-gh','A','ghana premier league odds'),
  ('1xb-gh','A','telecel cash betting'),
  ('1xb-gh','A','vodafone cash betting ghana'),
  ('1xb-gh','A','weekend jackpot ghana'),
  ('1xb-gh','A','betting bonus ghana today'),
  ('1xb-gh','A','aviator prediction ghana'),
  ('1xb-tz','A','mpesa tigo betting tanzania'),
  ('1xb-tz','A','jinsi ya kushinda kubet'),
  ('1xb-tz','A','tanzania premier league betting'),
  ('1xb-tz','A','azam fc betting'),
  ('1xb-tz','A','kamusi ya kubet'),
  ('1xb-tz','A','aviator tanzania mbinu'),
  ('1xb-tz','A','tigopesa betting deposit'),
  ('1xb-tz','A','ligi kuu bara odds'),
  ('1xb-ug','A','mtn momo betting uganda'),
  ('1xb-ug','A','uganda cranes betting'),
  ('1xb-ug','A','how to win aviator uganda'),
  ('1xb-ug','A','airtel money betting uganda'),
  ('1xb-ug','A','upl betting odds'),
  ('1xb-ug','A','jackpot prediction uganda'),
  ('1xb-ug','A','betpawa alternative uganda'),
  ('1xb-cm','A','om mobile money paris cameroun'),
  ('1xb-cm','A','comment gagner aviator cameroun'),
  ('1xb-cm','A','pronostic elite one'),
  ('1xb-cm','A','mtn momo paris cameroun'),
  ('1xb-cm','A','lions indomptables paris'),
  ('1xb-cm','A','orange money pari cameroun'),
  ('1xb-cm','A','astuce cash out cameroun'),
  ('1xb-ci','A','wave paris sportif civ'),
  ('1xb-ci','A','comment retirer gain 1x'),
  ('1xb-ci','A','pronostic ligue 1 ivoirienne'),
  ('1xb-ci','A','orange money pari abidjan'),
  ('1xb-ci','A','elephants paris preview'),
  ('1xb-ci','A','moov money paris civ'),
  ('1xb-ci','A','astuce aviator abidjan'),
  ('1xb-sn','A','wave paris senegal'),
  ('1xb-sn','A','comment gagner au pari senegal'),
  ('1xb-sn','A','lions teranga pari'),
  ('1xb-sn','A','orange money pari dakar'),
  ('1xb-sn','A','free money pari senegal'),
  ('1xb-sn','A','ligue 1 senegalaise cotes'),
  ('1xb-sn','A','astuce aviator dakar'),
  ('1xb-bf','A','orange money pari burkina'),
  ('1xb-bf','A','comment gagner pari ouaga'),
  ('1xb-bf','A','etalons pari preview'),
  ('1xb-bf','A','moov money pari burkina'),
  ('1xb-bf','A','coupon pari burkina'),
  ('1xb-bf','A','astuce aviator ouaga'),
  ('1xb-zm','A','airtel money betting zambia'),
  ('1xb-zm','A','chipolopolo betting'),
  ('1xb-zm','A','how to win aviator zambia'),
  ('1xb-zm','A','mtn momo betting zambia'),
  ('1xb-zm','A','zambia super league odds'),
  ('1xb-zm','A','jackpot prediction zambia'),
  ('1xb-cd','A','mpesa airtel pari rdc'),
  ('1xb-cd','A','comment gagner pari kinshasa'),
  ('1xb-cd','A','leopards pari preview'),
  ('1xb-cd','A','orange money pari rdc'),
  ('1xb-cd','A','ligue 1 rdc cotes'),
  ('1xb-cd','A','astuce aviator kinshasa'),
  ('1xb-et','A','telebirr betting ethiopia'),
  ('1xb-et','A','how to win aviator ethiopia'),
  ('1xb-et','A','ethiopia premier league odds'),
  ('1xb-et','A','cbe birr betting deposit'),
  ('1xb-et','A','jackpot prediction ethiopia'),
  ('1xb-et','A','ethiopia betting bonus'),
  ('1xb-mz','A','mpesa aposta mocambique'),
  ('1xb-mz','A','como ganhar aviator mocambique'),
  ('1xb-mz','A','mocambola apostas'),
  ('1xb-mz','A','emola aposta deposito'),
  ('1xb-mz','A','palancas apostas'),
  ('1xb-mz','A','dicas apostas mocambique'),
  ('1xb-ml','A','orange money pari mali'),
  ('1xb-ml','A','comment gagner pari bamako'),
  ('1xb-ml','A','aigles pari preview'),
  ('1xb-ml','A','moov money pari mali'),
  ('1xb-ml','A','astuce aviator bamako'),
  ('1xb-agency','A','africa betting traffic revshare'),
  ('1xb-agency','A','igaming africa media buyer'),
  ('1xb-agency','A','aviator africa signals'),
  ('1xb-agency','A','mobile money betting africa'),
  ('1xb-agency','A','afcon betting preview'),
  ('1xb-agency','A','african football prediction site'),
  ('1xb-agency','A','sports betting affiliate africa'),
  ('1xb-agency','A','casino traffic west africa')
) AS v(preset, layer, keyword)
ON CONFLICT (preset, keyword) DO NOTHING;

-- ── v6 pool: layer A (player intent), B (publisher), C (competitor footprint) ──
INSERT INTO public.keywords (preset, layer, keyword, lang, active)
SELECT v.preset, v.layer, v.keyword, v.lang, TRUE
FROM (VALUES
  ('1xb-ng','A','football prediction site nigeria today','en'),
  ('1xb-ng','A','sure banker prediction nigeria','en'),
  ('1xb-ng','A','naira withdrawal betting site fast','en'),
  ('1xb-ng','A','best odds nigeria premier league betting','en'),
  ('1xb-ng','A','accumulator tips nigeria weekend','en'),
  ('1xb-ng','A','virtual football league tips nigeria','en'),
  ('1xb-ng','A','booking code today nigeria','en'),
  ('1xb-ng','A','betting bonus code nigeria new customer','en'),
  ('1xb-ng','B','sports website advertise with us nigeria','en'),
  ('1xb-ng','B','media kit sports nigeria advertising rates','en'),
  ('1xb-ng','B','sponsored post sports blog nigeria','en'),
  ('1xb-ng','B','nigeria sports news partnerships advertising','en'),
  ('1xb-ng','B','advertise on our site sports nigeria','en'),
  ('1xb-ng','B','sports media nigeria advertising enquiries','en'),
  ('1xb-ng','B','nigeria digital publisher sports vertical','en'),
  ('1xb-ng','B','banner advertising sports site nigeria','en'),
  ('1xb-ng','C','bet9ja promo code nigeria review','en'),
  ('1xb-ng','C','sportybet promo code nigeria review','en'),
  ('1xb-ng','C','betking promo code nigeria review','en'),
  ('1xb-ng','C','nairabet promo code nigeria review','en'),
  ('1xb-ng','C','"affiliate links" betting site nigeria','en'),
  ('1xb-ng','C','"we may earn a commission" betting nigeria','en'),
  ('1xb-ng','C','"affiliate disclosure" sports betting nigeria','en'),
  ('1xb-ng','C','best betting sites nigeria review comparison','en'),
  ('1xb-ng','C','top bookmakers nigeria ranked review','en'),
  ('1xb-ng','C','nigeria bookmaker comparison bonus review','en'),
  ('1xb-ke','A','sure jackpot prediction kenya today','sw'),
  ('1xb-ke','A','tips za mchezo leo kenya','sw'),
  ('1xb-ke','A','kubeti na kushinda mkakati','sw'),
  ('1xb-ke','A','weekend jackpot bonus prediction kenya','sw'),
  ('1xb-ke','A','best betting odds comparison kenya','sw'),
  ('1xb-ke','A','utabiri wa mpira wa leo','sw'),
  ('1xb-ke','A','free betting tips kenya telegram','sw'),
  ('1xb-ke','A','kenya premier league betting preview','sw'),
  ('1xb-ke','B','sports website advertise with us kenya','sw'),
  ('1xb-ke','B','media kit sports kenya advertising rates','sw'),
  ('1xb-ke','B','sponsored post sports blog kenya','sw'),
  ('1xb-ke','B','kenya sports news partnerships advertising','sw'),
  ('1xb-ke','B','advertise on our site sports kenya','sw'),
  ('1xb-ke','B','sports media kenya advertising enquiries','sw'),
  ('1xb-ke','B','kenya digital publisher sports vertical','sw'),
  ('1xb-ke','B','banner advertising sports site kenya','sw'),
  ('1xb-ke','B','tangaza nasi michezo kenya','sw'),
  ('1xb-ke','C','sportpesa promo code kenya review','sw'),
  ('1xb-ke','C','betika promo code kenya review','sw'),
  ('1xb-ke','C','odibets promo code kenya review','sw'),
  ('1xb-ke','C','mozzartbet promo code kenya review','sw'),
  ('1xb-ke','C','"affiliate links" betting site kenya','sw'),
  ('1xb-ke','C','"we may earn a commission" betting kenya','sw'),
  ('1xb-ke','C','"affiliate disclosure" sports betting kenya','sw'),
  ('1xb-ke','C','best betting sites kenya review comparison','sw'),
  ('1xb-ke','C','top bookmakers kenya ranked review','sw'),
  ('1xb-ke','C','kenya bookmaker comparison bonus review','sw'),
  ('1xb-gh','A','ghana football prediction today free','en'),
  ('1xb-gh','A','banker of the day ghana betting','en'),
  ('1xb-gh','A','fastest payout betting site ghana','en'),
  ('1xb-gh','A','ghana premier league betting tips','en'),
  ('1xb-gh','A','double chance prediction ghana','en'),
  ('1xb-gh','A','betting cash out explained ghana','en'),
  ('1xb-gh','A','weekend banker ghana tips','en'),
  ('1xb-gh','A','odds analysis ghana bettors','en'),
  ('1xb-gh','B','sports website advertise with us ghana','en'),
  ('1xb-gh','B','media kit sports ghana advertising rates','en'),
  ('1xb-gh','B','sponsored post sports blog ghana','en'),
  ('1xb-gh','B','ghana sports news partnerships advertising','en'),
  ('1xb-gh','B','advertise on our site sports ghana','en'),
  ('1xb-gh','B','sports media ghana advertising enquiries','en'),
  ('1xb-gh','B','ghana digital publisher sports vertical','en'),
  ('1xb-gh','B','banner advertising sports site ghana','en'),
  ('1xb-gh','C','betway promo code ghana review','en'),
  ('1xb-gh','C','sportybet promo code ghana review','en'),
  ('1xb-gh','C','soccabet promo code ghana review','en'),
  ('1xb-gh','C','betpawa promo code ghana review','en'),
  ('1xb-gh','C','"affiliate links" betting site ghana','en'),
  ('1xb-gh','C','"we may earn a commission" betting ghana','en'),
  ('1xb-gh','C','"affiliate disclosure" sports betting ghana','en'),
  ('1xb-gh','C','best betting sites ghana review comparison','en'),
  ('1xb-gh','C','top bookmakers ghana ranked review','en'),
  ('1xb-gh','C','ghana bookmaker comparison bonus review','en'),
  ('1xb-tz','A','utabiri wa mpira tanzania leo','sw'),
  ('1xb-tz','A','bet ya uhakika leo tanzania','sw'),
  ('1xb-tz','A','mikakati ya kubeti tanzania','sw'),
  ('1xb-tz','A','jackpot prediction tanzania today','sw'),
  ('1xb-tz','A','ligi kuu tanzania betting tips','sw'),
  ('1xb-tz','A','namna ya kutoa pesa betting tanzania','sw'),
  ('1xb-tz','A','free tips mpira tanzania','sw'),
  ('1xb-tz','B','sports website advertise with us tanzania','sw'),
  ('1xb-tz','B','media kit sports tanzania advertising rates','sw'),
  ('1xb-tz','B','sponsored post sports blog tanzania','sw'),
  ('1xb-tz','B','tanzania sports news partnerships advertising','sw'),
  ('1xb-tz','B','advertise on our site sports tanzania','sw'),
  ('1xb-tz','B','sports media tanzania advertising enquiries','sw'),
  ('1xb-tz','B','tanzania digital publisher sports vertical','sw'),
  ('1xb-tz','B','banner advertising sports site tanzania','sw'),
  ('1xb-tz','B','matangazo tovuti michezo tanzania','sw'),
  ('1xb-tz','C','betway promo code tanzania review','sw'),
  ('1xb-tz','C','meridianbet promo code tanzania review','sw'),
  ('1xb-tz','C','premier bet promo code tanzania review','sw'),
  ('1xb-tz','C','betpawa promo code tanzania review','sw'),
  ('1xb-tz','C','"affiliate links" betting site tanzania','sw'),
  ('1xb-tz','C','"we may earn a commission" betting tanzania','sw'),
  ('1xb-tz','C','"affiliate disclosure" sports betting tanzania','sw'),
  ('1xb-tz','C','best betting sites tanzania review comparison','sw'),
  ('1xb-tz','C','top bookmakers tanzania ranked review','sw'),
  ('1xb-tz','C','tanzania bookmaker comparison bonus review','sw'),
  ('1xb-ug','A','uganda football prediction today','en'),
  ('1xb-ug','A','sure bet uganda telegram tips','en'),
  ('1xb-ug','A','best odds uganda betting sites','en'),
  ('1xb-ug','A','uganda premier league betting preview','en'),
  ('1xb-ug','A','jackpot tips uganda weekend','en'),
  ('1xb-ug','A','fast withdrawal betting uganda','en'),
  ('1xb-ug','B','sports website advertise with us uganda','en'),
  ('1xb-ug','B','media kit sports uganda advertising rates','en'),
  ('1xb-ug','B','sponsored post sports blog uganda','en'),
  ('1xb-ug','B','uganda sports news partnerships advertising','en'),
  ('1xb-ug','B','advertise on our site sports uganda','en'),
  ('1xb-ug','B','sports media uganda advertising enquiries','en'),
  ('1xb-ug','B','uganda digital publisher sports vertical','en'),
  ('1xb-ug','B','banner advertising sports site uganda','en'),
  ('1xb-ug','C','fortebet promo code uganda review','en'),
  ('1xb-ug','C','betway promo code uganda review','en'),
  ('1xb-ug','C','betpawa promo code uganda review','en'),
  ('1xb-ug','C','gal sport betting promo code uganda review','en'),
  ('1xb-ug','C','"affiliate links" betting site uganda','en'),
  ('1xb-ug','C','"we may earn a commission" betting uganda','en'),
  ('1xb-ug','C','"affiliate disclosure" sports betting uganda','en'),
  ('1xb-ug','C','best betting sites uganda review comparison','en'),
  ('1xb-ug','C','top bookmakers uganda ranked review','en'),
  ('1xb-ug','C','uganda bookmaker comparison bonus review','en'),
  ('1xb-cm','A','pronostic foot cameroun aujourd''hui','fr'),
  ('1xb-cm','A','meilleure cote paris sportif cameroun','fr'),
  ('1xb-cm','A','retrait rapide paris sportifs cameroun','fr'),
  ('1xb-cm','A','strategie paris combine cameroun','fr'),
  ('1xb-cm','A','pronostic elite one cameroun','fr'),
  ('1xb-cm','A','astuce jeux virtuels pari cameroun','fr'),
  ('1xb-cm','A','pronostiqueur fiable cameroun telegram','fr'),
  ('1xb-cm','B','regie publicitaire sport cameroun','fr'),
  ('1xb-cm','B','kit media site sport cameroun','fr'),
  ('1xb-cm','B','publicite site sportif cameroun tarifs','fr'),
  ('1xb-cm','B','article sponsorise sport cameroun','fr'),
  ('1xb-cm','B','partenariat commercial media sport cameroun','fr'),
  ('1xb-cm','C','code promo premier bet cameroun','fr'),
  ('1xb-cm','C','code promo 1win cameroun','fr'),
  ('1xb-cm','C','code promo betclic cameroun','fr'),
  ('1xb-cm','C','code promo parifoot cameroun','fr'),
  ('1xb-cm','C','"liens affilies" paris sportifs cameroun','fr'),
  ('1xb-cm','C','"partenaire officiel" pronostic cameroun','fr'),
  ('1xb-cm','C','meilleurs sites paris sportifs cameroun comparatif','fr'),
  ('1xb-ci','A','pronostic foot cote ivoire aujourd hui','fr'),
  ('1xb-ci','A','coupon du jour paris sportif abidjan','fr'),
  ('1xb-ci','A','comment retirer gains paris cote ivoire','fr'),
  ('1xb-ci','A','meilleur pronostiqueur abidjan telegram','fr'),
  ('1xb-ci','A','pronostic ligue 1 ivoirienne','fr'),
  ('1xb-ci','A','meilleure cote paris sportif abidjan','fr'),
  ('1xb-ci','A','strategie pari combine cote ivoire','fr'),
  ('1xb-ci','B','regie publicitaire sport cote ivoire','fr'),
  ('1xb-ci','B','kit media site sport cote ivoire','fr'),
  ('1xb-ci','B','publicite site sportif cote ivoire tarifs','fr'),
  ('1xb-ci','B','article sponsorise sport cote ivoire','fr'),
  ('1xb-ci','B','partenariat commercial media sport cote ivoire','fr'),
  ('1xb-ci','C','code promo premier bet cote ivoire','fr'),
  ('1xb-ci','C','code promo 1win cote ivoire','fr'),
  ('1xb-ci','C','code promo betclic cote ivoire','fr'),
  ('1xb-ci','C','"liens affilies" paris sportifs cote ivoire','fr'),
  ('1xb-ci','C','"partenaire officiel" pronostic cote ivoire','fr'),
  ('1xb-ci','C','meilleurs sites paris sportifs cote ivoire comparatif','fr'),
  ('1xb-sn','A','pronostic ligue 1 senegal aujourd hui','fr'),
  ('1xb-sn','A','coupon du jour paris sportif senegal','fr'),
  ('1xb-sn','A','comment retirer gains paris senegal','fr'),
  ('1xb-sn','A','meilleur pronostiqueur senegal telegram','fr'),
  ('1xb-sn','A','pari combine gagnant senegal','fr'),
  ('1xb-sn','A','analyse match ligue senegalaise','fr'),
  ('1xb-sn','A','bonus bienvenue paris sportifs senegal','fr'),
  ('1xb-sn','B','regie publicitaire sport senegal','fr'),
  ('1xb-sn','B','kit media site sport senegal','fr'),
  ('1xb-sn','B','publicite site sportif senegal tarifs','fr'),
  ('1xb-sn','B','article sponsorise sport senegal','fr'),
  ('1xb-sn','B','partenariat commercial media sport senegal','fr'),
  ('1xb-sn','C','code promo sunubet senegal','fr'),
  ('1xb-sn','C','code promo premier bet senegal','fr'),
  ('1xb-sn','C','code promo 1win senegal','fr'),
  ('1xb-sn','C','code promo betclic senegal','fr'),
  ('1xb-sn','C','"liens affilies" paris sportifs senegal','fr'),
  ('1xb-sn','C','"partenaire officiel" pronostic senegal','fr'),
  ('1xb-sn','C','meilleurs sites paris sportifs senegal comparatif','fr'),
  ('1xb-bf','A','pronostic foot burkina faso aujourd hui','fr'),
  ('1xb-bf','A','paris sportifs fiable ouagadougou','fr'),
  ('1xb-bf','A','coupon sur du jour burkina','fr'),
  ('1xb-bf','A','strategie pari sportif burkina faso','fr'),
  ('1xb-bf','A','meilleure cote pari burkina','fr'),
  ('1xb-bf','B','regie publicitaire sport burkina faso','fr'),
  ('1xb-bf','B','kit media site sport burkina faso','fr'),
  ('1xb-bf','B','publicite site sportif burkina faso tarifs','fr'),
  ('1xb-bf','B','article sponsorise sport burkina faso','fr'),
  ('1xb-bf','B','partenariat commercial media sport burkina faso','fr'),
  ('1xb-bf','C','code promo pmu''b burkina faso','fr'),
  ('1xb-bf','C','code promo premier bet burkina faso','fr'),
  ('1xb-bf','C','code promo 1win burkina faso','fr'),
  ('1xb-bf','C','"liens affilies" paris sportifs burkina faso','fr'),
  ('1xb-bf','C','"partenaire officiel" pronostic burkina faso','fr'),
  ('1xb-bf','C','meilleurs sites paris sportifs burkina faso comparatif','fr'),
  ('1xb-zm','A','zambia football prediction today','en'),
  ('1xb-zm','A','sure bet tips zambia telegram','en'),
  ('1xb-zm','A','fast withdrawal betting zambia','en'),
  ('1xb-zm','A','zambia super league betting preview','en'),
  ('1xb-zm','A','weekend accumulator tips zambia','en'),
  ('1xb-zm','B','sports website advertise with us zambia','en'),
  ('1xb-zm','B','media kit sports zambia advertising rates','en'),
  ('1xb-zm','B','sponsored post sports blog zambia','en'),
  ('1xb-zm','B','zambia sports news partnerships advertising','en'),
  ('1xb-zm','B','advertise on our site sports zambia','en'),
  ('1xb-zm','B','sports media zambia advertising enquiries','en'),
  ('1xb-zm','B','zambia digital publisher sports vertical','en'),
  ('1xb-zm','B','banner advertising sports site zambia','en'),
  ('1xb-zm','C','betway promo code zambia review','en'),
  ('1xb-zm','C','premier bet promo code zambia review','en'),
  ('1xb-zm','C','betpawa promo code zambia review','en'),
  ('1xb-zm','C','gal sport promo code zambia review','en'),
  ('1xb-zm','C','"affiliate links" betting site zambia','en'),
  ('1xb-zm','C','"we may earn a commission" betting zambia','en'),
  ('1xb-zm','C','"affiliate disclosure" sports betting zambia','en'),
  ('1xb-zm','C','best betting sites zambia review comparison','en'),
  ('1xb-zm','C','top bookmakers zambia ranked review','en'),
  ('1xb-zm','C','zambia bookmaker comparison bonus review','en'),
  ('1xb-cd','A','pronostic foot rdc aujourd hui','fr'),
  ('1xb-cd','A','paris sportifs kinshasa conseils','fr'),
  ('1xb-cd','A','coupon gagnant du jour rdc','fr'),
  ('1xb-cd','A','retrait paris sportifs congo mobile money','fr'),
  ('1xb-cd','A','meilleur pronostiqueur rdc','fr'),
  ('1xb-cd','A','linafoot pronostic','fr'),
  ('1xb-cd','B','regie publicitaire sport rdc','fr'),
  ('1xb-cd','B','kit media site sport rdc','fr'),
  ('1xb-cd','B','publicite site sportif rdc tarifs','fr'),
  ('1xb-cd','B','article sponsorise sport rdc','fr'),
  ('1xb-cd','B','partenariat commercial media sport rdc','fr'),
  ('1xb-cd','C','code promo premier bet rdc','fr'),
  ('1xb-cd','C','code promo betway rdc','fr'),
  ('1xb-cd','C','code promo 1win rdc','fr'),
  ('1xb-cd','C','"liens affilies" paris sportifs rdc','fr'),
  ('1xb-cd','C','"partenaire officiel" pronostic rdc','fr'),
  ('1xb-cd','C','meilleurs sites paris sportifs rdc comparatif','fr'),
  ('1xb-et','A','ethiopia football prediction today','en'),
  ('1xb-et','A','የቤት ትንበያ እግር ኳስ','en'),
  ('1xb-et','A','ethiopian premier league betting tips','en'),
  ('1xb-et','A','sure odds ethiopia telegram','en'),
  ('1xb-et','A','best betting site ethiopia payout','en'),
  ('1xb-et','B','sports website advertise with us ethiopia','en'),
  ('1xb-et','B','media kit sports ethiopia advertising rates','en'),
  ('1xb-et','B','sponsored post sports blog ethiopia','en'),
  ('1xb-et','B','ethiopia sports news partnerships advertising','en'),
  ('1xb-et','B','advertise on our site sports ethiopia','en'),
  ('1xb-et','B','sports media ethiopia advertising enquiries','en'),
  ('1xb-et','B','ethiopia digital publisher sports vertical','en'),
  ('1xb-et','B','banner advertising sports site ethiopia','en'),
  ('1xb-et','C','hulusport promo code ethiopia review','en'),
  ('1xb-et','C','abyssinia bet promo code ethiopia review','en'),
  ('1xb-et','C','habesha bet promo code ethiopia review','en'),
  ('1xb-et','C','"affiliate links" betting site ethiopia','en'),
  ('1xb-et','C','"we may earn a commission" betting ethiopia','en'),
  ('1xb-et','C','"affiliate disclosure" sports betting ethiopia','en'),
  ('1xb-et','C','best betting sites ethiopia review comparison','en'),
  ('1xb-et','C','top bookmakers ethiopia ranked review','en'),
  ('1xb-et','C','ethiopia bookmaker comparison bonus review','en'),
  ('1xb-mz','A','prognosticos futebol mocambique hoje','pt'),
  ('1xb-mz','A','dicas de apostas mocambique','pt'),
  ('1xb-mz','A','como levantar dinheiro apostas mocambique','pt'),
  ('1xb-mz','A','melhores odds apostas mocambique','pt'),
  ('1xb-mz','A','palpites do dia mocambique futebol','pt'),
  ('1xb-mz','A','mocambola apostas analise','pt'),
  ('1xb-mz','B','publicidade site desporto mocambique','pt'),
  ('1xb-mz','B','kit de media desporto mocambique','pt'),
  ('1xb-mz','B','artigo patrocinado apostas mocambique','pt'),
  ('1xb-mz','C','codigo promocional premier bet mocambique','pt'),
  ('1xb-mz','C','codigo promocional betpawa mocambique','pt'),
  ('1xb-mz','C','codigo promocional betway mocambique','pt'),
  ('1xb-mz','C','"affiliate links" betting site mocambique','pt'),
  ('1xb-mz','C','"we may earn a commission" betting mocambique','pt'),
  ('1xb-mz','C','"affiliate disclosure" sports betting mocambique','pt'),
  ('1xb-mz','C','melhores casas de apostas mocambique analise','pt'),
  ('1xb-ml','A','pronostic foot mali aujourd hui','fr'),
  ('1xb-ml','A','paris sportifs bamako conseils','fr'),
  ('1xb-ml','A','coupon du jour mali pari','fr'),
  ('1xb-ml','A','meilleur site pari sportif mali retrait','fr'),
  ('1xb-ml','B','regie publicitaire sport mali','fr'),
  ('1xb-ml','B','kit media site sport mali','fr'),
  ('1xb-ml','B','publicite site sportif mali tarifs','fr'),
  ('1xb-ml','B','article sponsorise sport mali','fr'),
  ('1xb-ml','B','partenariat commercial media sport mali','fr'),
  ('1xb-ml','C','code promo premier bet mali','fr'),
  ('1xb-ml','C','code promo 1win mali','fr'),
  ('1xb-ml','C','code promo pmu mali mali','fr'),
  ('1xb-ml','C','"liens affilies" paris sportifs mali','fr'),
  ('1xb-ml','C','"partenaire officiel" pronostic mali','fr'),
  ('1xb-ml','C','meilleurs sites paris sportifs mali comparatif','fr'),
  ('1xb-agency','A','african football prediction site','en'),
  ('1xb-agency','A','caf champions league betting tips','en'),
  ('1xb-agency','A','afcon betting preview odds','en'),
  ('1xb-agency','A','pronostic can afrique','en'),
  ('1xb-agency','A','best african betting tipster telegram','en'),
  ('1xb-agency','A','free daily tips africa football','en'),
  ('1xb-agency','B','sports website advertise with us africa','en'),
  ('1xb-agency','B','media kit sports africa advertising rates','en'),
  ('1xb-agency','B','sponsored post sports blog africa','en'),
  ('1xb-agency','B','africa sports news partnerships advertising','en'),
  ('1xb-agency','B','advertise on our site sports africa','en'),
  ('1xb-agency','B','sports media africa advertising enquiries','en'),
  ('1xb-agency','B','africa digital publisher sports vertical','en'),
  ('1xb-agency','B','banner advertising sports site africa','en'),
  ('1xb-agency','C','betway promo code africa review','en'),
  ('1xb-agency','C','premier bet promo code africa review','en'),
  ('1xb-agency','C','1win promo code africa review','en'),
  ('1xb-agency','C','betpawa promo code africa review','en'),
  ('1xb-agency','C','"affiliate links" betting site africa','en'),
  ('1xb-agency','C','"we may earn a commission" betting africa','en'),
  ('1xb-agency','C','"affiliate disclosure" sports betting africa','en'),
  ('1xb-agency','C','best betting sites africa review comparison','en'),
  ('1xb-agency','C','top bookmakers africa ranked review','en'),
  ('1xb-agency','C','africa bookmaker comparison bonus review','en')
) AS v(preset, layer, keyword, lang)
ON CONFLICT (preset, keyword) DO NOTHING;

-- ── Top-up so no preset/layer starts below the pool-depth alert threshold ──
-- archive-keywords warns when a preset+layer drops under 5 active keywords. The
-- Portuguese (MZ/B) and Mali (ML/A) sets came out of the brief short of that, and
-- a fresh pool firing a "pool exhausted" alert on day one is a false alarm.
INSERT INTO public.keywords (preset, layer, keyword, lang, active)
SELECT v.preset, v.layer, v.keyword, v.lang, TRUE
FROM (VALUES
  ('1xb-mz','B','anunciar no nosso site desporto mocambique','pt'),
  ('1xb-mz','B','tarifas publicidade desporto mocambique','pt'),
  ('1xb-mz','B','parceria comercial media desporto mocambique','pt'),
  ('1xb-ml','A','pronostic ligue 1 malienne aujourd hui','fr'),
  ('1xb-ml','A','meilleur pronostiqueur mali telegram','fr'),
  ('1xb-bf','A','pronostiqueur fiable burkina telegram','fr'),
  ('1xb-et','A','ethiopia betting tips telegram channel','en'),
  ('1xb-zm','A','zambia betting prediction telegram tips','en')
) AS v(preset, layer, keyword, lang)
ON CONFLICT (preset, keyword) DO NOTHING;
