-- v6.2: fresh-angle keyword batch to reach African site inventory the mined
-- player-intent pool never touched — casino/slots, Aviator/crash, European club
-- football (Africans bet heavily on EPL/UCL), Telegram/WhatsApp tip channels,
-- esports and crypto betting. All layer A, active. The per-keyword yield tracking
-- (archive-keywords) will keep the productive ones and retire the rest, so this is
-- a measured experiment, not a permanent bloat. Idempotent via ON CONFLICT.
INSERT INTO public.keywords (preset, layer, keyword, lang, active)
SELECT v.preset, v.layer, v.keyword, v.lang, TRUE
FROM (VALUES
  ('1xb-ng','A','best online casino nigeria review','en'),
  ('1xb-ng','A','casino bonus nigeria free spins','en'),
  ('1xb-ng','A','slot games real money nigeria','en'),
  ('1xb-ng','A','aviator prediction nigeria telegram','en'),
  ('1xb-ng','A','aviator signals nigeria today','en'),
  ('1xb-ng','A','premier league prediction nigeria blog','en'),
  ('1xb-ng','A','champions league betting tips nigeria','en'),
  ('1xb-ng','A','epl accumulator tips nigeria','en'),
  ('1xb-ng','A','telegram betting tips channel nigeria','en'),
  ('1xb-ng','A','whatsapp betting group nigeria free tips','en'),
  ('1xb-ng','A','esports betting tips nigeria','en'),
  ('1xb-ng','A','crypto betting sites nigeria','en'),
  ('1xb-ke','A','best online casino kenya review','en'),
  ('1xb-ke','A','casino bonus kenya free spins','en'),
  ('1xb-ke','A','slot games real money kenya','en'),
  ('1xb-ke','A','aviator prediction kenya telegram','en'),
  ('1xb-ke','A','aviator signals kenya today','en'),
  ('1xb-ke','A','premier league prediction kenya blog','en'),
  ('1xb-ke','A','champions league betting tips kenya','en'),
  ('1xb-ke','A','epl accumulator tips kenya','en'),
  ('1xb-ke','A','telegram betting tips channel kenya','en'),
  ('1xb-ke','A','whatsapp betting group kenya free tips','en'),
  ('1xb-ke','A','esports betting tips kenya','en'),
  ('1xb-ke','A','crypto betting sites kenya','en'),
  ('1xb-gh','A','best online casino ghana review','en'),
  ('1xb-gh','A','casino bonus ghana free spins','en'),
  ('1xb-gh','A','slot games real money ghana','en'),
  ('1xb-gh','A','aviator prediction ghana telegram','en'),
  ('1xb-gh','A','aviator signals ghana today','en'),
  ('1xb-gh','A','premier league prediction ghana blog','en'),
  ('1xb-gh','A','champions league betting tips ghana','en'),
  ('1xb-gh','A','epl accumulator tips ghana','en'),
  ('1xb-gh','A','telegram betting tips channel ghana','en'),
  ('1xb-gh','A','whatsapp betting group ghana free tips','en'),
  ('1xb-gh','A','esports betting tips ghana','en'),
  ('1xb-gh','A','crypto betting sites ghana','en'),
  ('1xb-tz','A','best online casino tanzania review','en'),
  ('1xb-tz','A','casino bonus tanzania free spins','en'),
  ('1xb-tz','A','slot games real money tanzania','en'),
  ('1xb-tz','A','aviator prediction tanzania telegram','en'),
  ('1xb-tz','A','aviator signals tanzania today','en'),
  ('1xb-tz','A','premier league prediction tanzania blog','en'),
  ('1xb-tz','A','champions league betting tips tanzania','en'),
  ('1xb-tz','A','epl accumulator tips tanzania','en'),
  ('1xb-tz','A','telegram betting tips channel tanzania','en'),
  ('1xb-tz','A','whatsapp betting group tanzania free tips','en'),
  ('1xb-tz','A','esports betting tips tanzania','en'),
  ('1xb-tz','A','crypto betting sites tanzania','en'),
  ('1xb-ug','A','best online casino uganda review','en'),
  ('1xb-ug','A','casino bonus uganda free spins','en'),
  ('1xb-ug','A','slot games real money uganda','en'),
  ('1xb-ug','A','aviator prediction uganda telegram','en'),
  ('1xb-ug','A','aviator signals uganda today','en'),
  ('1xb-ug','A','premier league prediction uganda blog','en'),
  ('1xb-ug','A','champions league betting tips uganda','en'),
  ('1xb-ug','A','epl accumulator tips uganda','en'),
  ('1xb-ug','A','telegram betting tips channel uganda','en'),
  ('1xb-ug','A','whatsapp betting group uganda free tips','en'),
  ('1xb-ug','A','esports betting tips uganda','en'),
  ('1xb-ug','A','crypto betting sites uganda','en'),
  ('1xb-cm','A','meilleur casino en ligne cameroun avis','fr'),
  ('1xb-cm','A','bonus casino cameroun tours gratuits','fr'),
  ('1xb-cm','A','machines a sous argent reel cameroun','fr'),
  ('1xb-cm','A','pronostic aviator cameroun telegram','fr'),
  ('1xb-cm','A','signaux aviator cameroun aujourd hui','fr'),
  ('1xb-cm','A','pronostic premier league cameroun blog','fr'),
  ('1xb-cm','A','pronostic ligue des champions cameroun','fr'),
  ('1xb-cm','A','combine ligue des champions cameroun','fr'),
  ('1xb-cm','A','canal telegram pronostic cameroun','fr'),
  ('1xb-cm','A','groupe whatsapp pronostic cameroun','fr'),
  ('1xb-cm','A','paris esport cameroun pronostic','fr'),
  ('1xb-cm','A','paris crypto cameroun bookmaker','fr'),
  ('1xb-ci','A','meilleur casino en ligne cote ivoire avis','fr'),
  ('1xb-ci','A','bonus casino cote ivoire tours gratuits','fr'),
  ('1xb-ci','A','machines a sous argent reel cote ivoire','fr'),
  ('1xb-ci','A','pronostic aviator cote ivoire telegram','fr'),
  ('1xb-ci','A','signaux aviator cote ivoire aujourd hui','fr'),
  ('1xb-ci','A','pronostic premier league cote ivoire blog','fr'),
  ('1xb-ci','A','pronostic ligue des champions cote ivoire','fr'),
  ('1xb-ci','A','combine ligue des champions cote ivoire','fr'),
  ('1xb-ci','A','canal telegram pronostic cote ivoire','fr'),
  ('1xb-ci','A','groupe whatsapp pronostic cote ivoire','fr'),
  ('1xb-ci','A','paris esport cote ivoire pronostic','fr'),
  ('1xb-ci','A','paris crypto cote ivoire bookmaker','fr'),
  ('1xb-sn','A','meilleur casino en ligne senegal avis','fr'),
  ('1xb-sn','A','bonus casino senegal tours gratuits','fr'),
  ('1xb-sn','A','machines a sous argent reel senegal','fr'),
  ('1xb-sn','A','pronostic aviator senegal telegram','fr'),
  ('1xb-sn','A','signaux aviator senegal aujourd hui','fr'),
  ('1xb-sn','A','pronostic premier league senegal blog','fr'),
  ('1xb-sn','A','pronostic ligue des champions senegal','fr'),
  ('1xb-sn','A','combine ligue des champions senegal','fr'),
  ('1xb-sn','A','canal telegram pronostic senegal','fr'),
  ('1xb-sn','A','groupe whatsapp pronostic senegal','fr'),
  ('1xb-sn','A','paris esport senegal pronostic','fr'),
  ('1xb-sn','A','paris crypto senegal bookmaker','fr'),
  ('1xb-bf','A','meilleur casino en ligne burkina faso avis','fr'),
  ('1xb-bf','A','bonus casino burkina faso tours gratuits','fr'),
  ('1xb-bf','A','machines a sous argent reel burkina faso','fr'),
  ('1xb-bf','A','pronostic aviator burkina faso telegram','fr'),
  ('1xb-bf','A','signaux aviator burkina faso aujourd hui','fr'),
  ('1xb-bf','A','pronostic premier league burkina faso blog','fr'),
  ('1xb-bf','A','pronostic ligue des champions burkina faso','fr'),
  ('1xb-bf','A','combine ligue des champions burkina faso','fr'),
  ('1xb-bf','A','canal telegram pronostic burkina faso','fr'),
  ('1xb-bf','A','groupe whatsapp pronostic burkina faso','fr'),
  ('1xb-bf','A','paris esport burkina faso pronostic','fr'),
  ('1xb-bf','A','paris crypto burkina faso bookmaker','fr'),
  ('1xb-zm','A','best online casino zambia review','en'),
  ('1xb-zm','A','casino bonus zambia free spins','en'),
  ('1xb-zm','A','slot games real money zambia','en'),
  ('1xb-zm','A','aviator prediction zambia telegram','en'),
  ('1xb-zm','A','aviator signals zambia today','en'),
  ('1xb-zm','A','premier league prediction zambia blog','en'),
  ('1xb-zm','A','champions league betting tips zambia','en'),
  ('1xb-zm','A','epl accumulator tips zambia','en'),
  ('1xb-zm','A','telegram betting tips channel zambia','en'),
  ('1xb-zm','A','whatsapp betting group zambia free tips','en'),
  ('1xb-zm','A','esports betting tips zambia','en'),
  ('1xb-zm','A','crypto betting sites zambia','en'),
  ('1xb-cd','A','meilleur casino en ligne rdc avis','fr'),
  ('1xb-cd','A','bonus casino rdc tours gratuits','fr'),
  ('1xb-cd','A','machines a sous argent reel rdc','fr'),
  ('1xb-cd','A','pronostic aviator rdc telegram','fr'),
  ('1xb-cd','A','signaux aviator rdc aujourd hui','fr'),
  ('1xb-cd','A','pronostic premier league rdc blog','fr'),
  ('1xb-cd','A','pronostic ligue des champions rdc','fr'),
  ('1xb-cd','A','combine ligue des champions rdc','fr'),
  ('1xb-cd','A','canal telegram pronostic rdc','fr'),
  ('1xb-cd','A','groupe whatsapp pronostic rdc','fr'),
  ('1xb-cd','A','paris esport rdc pronostic','fr'),
  ('1xb-cd','A','paris crypto rdc bookmaker','fr'),
  ('1xb-et','A','best online casino ethiopia review','en'),
  ('1xb-et','A','casino bonus ethiopia free spins','en'),
  ('1xb-et','A','slot games real money ethiopia','en'),
  ('1xb-et','A','aviator prediction ethiopia telegram','en'),
  ('1xb-et','A','aviator signals ethiopia today','en'),
  ('1xb-et','A','premier league prediction ethiopia blog','en'),
  ('1xb-et','A','champions league betting tips ethiopia','en'),
  ('1xb-et','A','epl accumulator tips ethiopia','en'),
  ('1xb-et','A','telegram betting tips channel ethiopia','en'),
  ('1xb-et','A','whatsapp betting group ethiopia free tips','en'),
  ('1xb-et','A','esports betting tips ethiopia','en'),
  ('1xb-et','A','crypto betting sites ethiopia','en'),
  ('1xb-mz','A','melhor casino online mocambique analise','pt'),
  ('1xb-mz','A','bonus casino mocambique rodadas gratis','pt'),
  ('1xb-mz','A','slots dinheiro real mocambique','pt'),
  ('1xb-mz','A','previsao aviator mocambique telegram','pt'),
  ('1xb-mz','A','sinais aviator mocambique hoje','pt'),
  ('1xb-mz','A','prognostico premier league mocambique','pt'),
  ('1xb-mz','A','dicas liga dos campeoes mocambique','pt'),
  ('1xb-mz','A','canal telegram apostas mocambique','pt'),
  ('1xb-mz','A','grupo whatsapp apostas mocambique','pt'),
  ('1xb-mz','A','apostas esports mocambique','pt'),
  ('1xb-ml','A','meilleur casino en ligne mali avis','fr'),
  ('1xb-ml','A','bonus casino mali tours gratuits','fr'),
  ('1xb-ml','A','machines a sous argent reel mali','fr'),
  ('1xb-ml','A','pronostic aviator mali telegram','fr'),
  ('1xb-ml','A','signaux aviator mali aujourd hui','fr'),
  ('1xb-ml','A','pronostic premier league mali blog','fr'),
  ('1xb-ml','A','pronostic ligue des champions mali','fr'),
  ('1xb-ml','A','combine ligue des champions mali','fr'),
  ('1xb-ml','A','canal telegram pronostic mali','fr'),
  ('1xb-ml','A','groupe whatsapp pronostic mali','fr'),
  ('1xb-ml','A','paris esport mali pronostic','fr'),
  ('1xb-ml','A','paris crypto mali bookmaker','fr'),
  ('1xb-agency','A','best online casino africa review','en'),
  ('1xb-agency','A','casino bonus africa free spins','en'),
  ('1xb-agency','A','slot games real money africa','en'),
  ('1xb-agency','A','aviator prediction africa telegram','en'),
  ('1xb-agency','A','aviator signals africa today','en'),
  ('1xb-agency','A','premier league prediction africa blog','en'),
  ('1xb-agency','A','champions league betting tips africa','en'),
  ('1xb-agency','A','epl accumulator tips africa','en'),
  ('1xb-agency','A','telegram betting tips channel africa','en'),
  ('1xb-agency','A','whatsapp betting group africa free tips','en'),
  ('1xb-agency','A','esports betting tips africa','en'),
  ('1xb-agency','A','crypto betting sites africa','en')
) AS v(preset, layer, keyword, lang)
ON CONFLICT (preset, keyword) DO NOTHING;
