-- 040 — Блок 2: keyword-пулы для multibrand_keywords (1xCasino, LuckyPari)
--
-- Данные от Ника (AffiliateOS_KeywordPools_1xCasino_LuckyPari.sql), с двумя
-- правками при переносе:
--
-- 1. Уникальный индекс + ON CONFLICT DO NOTHING — миграция должна быть
--    безопасна при повторном запуске, как и весь остальной репозиторий
--    (см. 016_search_v6.sql: тот же принцип на старой keywords).
--
-- 2. БАГ в исходнике: luckypari/somalia была списана с 1xcasino/somalia
--    один в один — те же казино-формулировки ("casino online ugu
--    wanaagsan" / "casino bonus code") под LuckyPari, который
--    vertical=standard (беттинг, не казино), плюс отсутствовала AR-пара
--    и layer B — единственное гео во всём файле без layer B. Заменено на
--    беттинг-формулировки; AR-фразы взяты из уже проверенных в этом же
--    файле пар Egypt/Morocco ("أفضل مواقع المراهنات" / "كود بونص
--    مراهنات"), а не придуманы заново.
--
-- Как и предупреждал автор сида: часть языков (KK/KY/MN/SI/UR/SO/AZ/MY)
-- сгенерирована по шаблону без проверки носителем — смотреть funnel_stats
-- по этим языкам отдельно первую неделю, <3 результата на запрос стабильно
-- значит переписать или выключить active=false.
--
-- ВНИМАНИЕ: multibrand_keywords само по себе НЕ подключено как источник ключей
-- в find-and-queue.ts (см. комментарий в 038_multibrand_execution_layer.sql) —
-- эти строки лежат в базе, но пайплайн их пока не читает. Подключение
-- источника — отдельная работа, не эта миграция.

CREATE UNIQUE INDEX IF NOT EXISTS multibrand_keywords_dedup
  ON public.multibrand_keywords (brand_id, geo, language, keyword);

-- ============================================
-- multibrand_keywords seed: 1xcasino
-- ============================================

INSERT INTO public.multibrand_keywords (brand_id, geo, language, keyword, layer, active) VALUES
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'guinea', 'FR', 'meilleur casino en ligne Guinea', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'guinea', 'FR', 'code bonus casino Guinea', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'guinea', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'niger', 'FR', 'meilleur casino en ligne Niger', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'niger', 'FR', 'code bonus casino Niger', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'niger', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ghana', 'EN', 'best online casino Ghana', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ghana', 'EN', 'Ghana casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ghana', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'zambia', 'EN', 'best online casino Zambia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'zambia', 'EN', 'Zambia casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'zambia', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_africa', 'EN', 'best online casino South Africa', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_africa', 'EN', 'South Africa casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_africa', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'nigeria', 'EN', 'best online casino Nigeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'nigeria', 'EN', 'Nigeria casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'nigeria', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kenya', 'EN', 'best online casino Kenya', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kenya', 'EN', 'Kenya casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kenya', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'burkina_faso', 'FR', 'meilleur casino en ligne Burkina Faso', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'burkina_faso', 'FR', 'code bonus casino Burkina Faso', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'burkina_faso', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cameroon', 'FR', 'meilleur casino en ligne Cameroon', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cameroon', 'FR', 'code bonus casino Cameroon', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cameroon', 'EN', 'best online casino Cameroon', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cameroon', 'EN', 'Cameroon casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cameroon', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'benin', 'FR', 'meilleur casino en ligne Benin', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'benin', 'FR', 'code bonus casino Benin', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'benin', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'senegal', 'FR', 'meilleur casino en ligne Senegal', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'senegal', 'FR', 'code bonus casino Senegal', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'senegal', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'togo', 'FR', 'meilleur casino en ligne Togo', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'togo', 'FR', 'code bonus casino Togo', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'togo', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cote_divoire', 'FR', 'meilleur casino en ligne Cote d''Ivoire', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cote_divoire', 'FR', 'code bonus casino Cote d''Ivoire', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'cote_divoire', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'colombia', 'ES', 'mejor casino online Colombia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'colombia', 'ES', 'bono casino Colombia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'colombia', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ecuador', 'ES', 'mejor casino online Ecuador', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ecuador', 'ES', 'bono casino Ecuador', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'ecuador', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bolivia', 'ES', 'mejor casino online Bolivia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bolivia', 'ES', 'bono casino Bolivia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bolivia', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'venezuela', 'ES', 'mejor casino online Venezuela', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'venezuela', 'ES', 'bono casino Venezuela', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'venezuela', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'peru', 'ES', 'mejor casino online Peru', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'peru', 'ES', 'bono casino Peru', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'peru', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'chile', 'ES', 'mejor casino online Chile', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'chile', 'ES', 'bono casino Chile', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'chile', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'brazil', 'PT', 'melhor cassino online Brazil', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'brazil', 'PT', 'codigo bonus cassino Brazil', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'brazil', 'PT', 'programa de afiliados cassino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'russia', 'RU', 'лучшее онлайн казино Russia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'russia', 'RU', 'казино бонус промокод Russia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'russia', 'RU', 'партнёрская программа казино', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'azerbaijan', 'AZ', 'ən yaxşı onlayn kazino Azerbaijan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'azerbaijan', 'AZ', 'kazino bonus kodu Azerbaijan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'azerbaijan', 'RU', 'лучшее онлайн казино Azerbaijan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'azerbaijan', 'RU', 'казино бонус промокод Azerbaijan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'azerbaijan', 'AZ', 'kazino ortaqlıq proqramı', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'egypt', 'AR', 'أفضل كازينو اونلاين Egypt', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'egypt', 'AR', 'كود بونص كازينو Egypt', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'egypt', 'AR', 'برنامج الشراكة كازينو', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'somalia', 'SO', 'casino online ugu wanaagsan Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'somalia', 'SO', 'casino bonus code Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'somalia', 'AR', 'أفضل كازينو اونلاين Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'somalia', 'AR', 'كود بونص كازينو Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'somalia', 'SO', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'uzbekistan', 'UZ', 'eng yaxshi onlayn kazino Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'uzbekistan', 'UZ', 'kazino bonus kodi Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'uzbekistan', 'RU', 'лучшее онлайн казино Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'uzbekistan', 'RU', 'казино бонус промокод Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'uzbekistan', 'UZ', 'kazino sheriklik dasturi', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'turkey', 'TR', 'en iyi online casino Turkey', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'turkey', 'TR', 'casino bonus kodu Turkey', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'turkey', 'TR', 'casino ortaklık programı', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_korea', 'KO', 'South Korea 온라인 카지노 추천', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_korea', 'KO', '카지노 보너스 코드 South Korea', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'south_korea', 'KO', '카지노 제휴 프로그램', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kyrgyzstan', 'KY', 'eñ jakshy onlayn kazino Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kyrgyzstan', 'KY', 'kazino bonus kodu Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kyrgyzstan', 'RU', 'лучшее онлайн казино Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kyrgyzstan', 'RU', 'казино бонус промокод Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kyrgyzstan', 'KY', 'казино партнёрлык программасы', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'algeria', 'FR', 'meilleur casino en ligne Algeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'algeria', 'FR', 'code bonus casino Algeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'algeria', 'AR', 'أفضل كازينو اونلاين Algeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'algeria', 'AR', 'كود بونص كازينو Algeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'algeria', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bangladesh', 'BN', 'সেরা অনলাইন ক্যাসিনো Bangladesh', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bangladesh', 'BN', 'ক্যাসিনো বোনাস কোড Bangladesh', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'bangladesh', 'BN', 'ক্যাসিনো অ্যাফিলিয়েট প্রোগ্রাম', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'morocco', 'FR', 'meilleur casino en ligne Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'morocco', 'FR', 'code bonus casino Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'morocco', 'AR', 'أفضل كازينو اونلاين Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'morocco', 'AR', 'كود بونص كازينو Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'morocco', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'india', 'EN', 'best online casino India', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'india', 'EN', 'India casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'india', 'HI', 'सबसे अच्छा ऑनलाइन कैसीनो India', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'india', 'HI', 'कैसीनो बोनस कोड India', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'india', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'canada', 'EN', 'best online casino Canada', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'canada', 'EN', 'Canada casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'canada', 'FR', 'meilleur casino en ligne Canada', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'canada', 'FR', 'code bonus casino Canada', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'canada', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'pakistan', 'EN', 'best online casino Pakistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'pakistan', 'EN', 'Pakistan casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'pakistan', 'UR', 'بہترین آن لائن کیسینو Pakistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'pakistan', 'UR', 'کیسینو بونس کوڈ Pakistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'pakistan', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'sri_lanka', 'EN', 'best online casino Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'sri_lanka', 'EN', 'Sri Lanka casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'sri_lanka', 'SI', 'senaga online casino Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'sri_lanka', 'SI', 'casino bonus code Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'sri_lanka', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'japan', 'JA', 'Japan オンラインカジノ おすすめ', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'japan', 'JA', 'カジノ ボーナスコード Japan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'japan', 'JA', 'カジノ アフィリエイト プログラム', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'myanmar', 'MY', 'Myanmar အွန်လိုင်း ကာစီနို', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'myanmar', 'MY', 'ကာစီနို ဘောနပ်စ် ကုဒ် Myanmar', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'philippines', 'EN', 'best online casino Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'philippines', 'EN', 'Philippines casino bonus codes', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'philippines', 'TL', 'pinakamagandang online casino Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'philippines', 'TL', 'casino bonus code Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'philippines', 'EN', 'casino affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'argentina', 'ES', 'mejor casino online Argentina', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'argentina', 'ES', 'bono casino Argentina', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'argentina', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mauritania', 'FR', 'meilleur casino en ligne Mauritania', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mauritania', 'FR', 'code bonus casino Mauritania', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mauritania', 'AR', 'أفضل كازينو اونلاين Mauritania', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mauritania', 'AR', 'كود بونص كازينو Mauritania', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mauritania', 'FR', 'programme d''affiliation casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kazakhstan', 'KK', 'eñ jaqsy onlain kazinosy Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kazakhstan', 'KK', 'kazino bonus kody Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kazakhstan', 'RU', 'лучшее онлайн казино Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kazakhstan', 'RU', 'казино бонус промокод Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'kazakhstan', 'KK', 'казино серіктестік бағдарламасы', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mongolia', 'MN', 'shildeg online казино Mongolia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mongolia', 'MN', 'казино бонус код Mongolia', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mexico', 'ES', 'mejor casino online Mexico', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mexico', 'ES', 'bono casino Mexico', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'mexico', 'ES', 'programa de afiliados casino', 'B', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'iran', 'FA', 'بهترین کازینو آنلاین Iran', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'iran', 'FA', 'کد بونوس کازینو Iran', 'A', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'global', 'EN', 'inurl:casino-review "bonus code"', 'C', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'global', 'EN', 'site:blogspot.com "casino bonus" review', 'C', true),
((SELECT id FROM public.brands WHERE slug='1xcasino'), 'global', 'EN', '"casino affiliate" "contact us" blog', 'C', true)
ON CONFLICT (brand_id, geo, language, keyword) DO NOTHING;

-- ============================================
-- multibrand_keywords seed: luckypari
-- ============================================

INSERT INTO public.multibrand_keywords (brand_id, geo, language, keyword, layer, active) VALUES
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uzbekistan', 'UZ', 'eng yaxshi bukmekerlik Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uzbekistan', 'UZ', 'bukmeker bonus kodi Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uzbekistan', 'RU', 'лучшие сайты для ставок Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uzbekistan', 'RU', 'промокод букмекер Uzbekistan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uzbekistan', 'UZ', 'sheriklik dasturi bukmeker', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'russia', 'RU', 'лучшие сайты для ставок Russia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'russia', 'RU', 'промокод букмекер Russia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'russia', 'RU', 'партнёрская программа букмекера', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kazakhstan', 'KK', 'eñ jaqsy bukmekerlik keñsesi Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kazakhstan', 'KK', 'bukmeker bonus kody Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kazakhstan', 'RU', 'лучшие сайты для ставок Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kazakhstan', 'RU', 'промокод букмекер Kazakhstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kazakhstan', 'KK', 'букмекер серіктестік бағдарламасы', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kyrgyzstan', 'KY', 'eñ jakshy bukmekerlik Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kyrgyzstan', 'KY', 'bukmeker bonus kodu Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kyrgyzstan', 'RU', 'лучшие сайты для ставок Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kyrgyzstan', 'RU', 'промокод букмекер Kyrgyzstan', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kyrgyzstan', 'KY', 'букмекер өнөктөштүк программасы', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'bangladesh', 'BN', 'সেরা বেটিং সাইট Bangladesh', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'bangladesh', 'BN', 'বেটিং বোনাস কোড Bangladesh', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'bangladesh', 'BN', 'বেটিং অ্যাফিলিয়েট প্রোগ্রাম', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'sri_lanka', 'EN', 'best betting sites Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'sri_lanka', 'EN', 'Sri Lanka bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'sri_lanka', 'SI', 'senaga betting site Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'sri_lanka', 'SI', 'betting bonus code Sri Lanka', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'sri_lanka', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'philippines', 'EN', 'best betting sites Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'philippines', 'EN', 'Philippines bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'philippines', 'TL', 'pinakamagandang betting site Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'philippines', 'TL', 'betting bonus code Philippines', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'philippines', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'egypt', 'AR', 'أفضل مواقع المراهنات Egypt', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'egypt', 'AR', 'كود بونص مراهنات Egypt', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'egypt', 'AR', 'برنامج الشراكة مراهنات', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'morocco', 'FR', 'meilleurs sites paris sportifs Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'morocco', 'FR', 'code bonus pari sportif Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'morocco', 'AR', 'أفضل مواقع المراهنات Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'morocco', 'AR', 'كود بونص مراهنات Morocco', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'morocco', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'somalia', 'EN', 'best betting sites Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'somalia', 'EN', 'Somalia bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'somalia', 'AR', 'أفضل مواقع المراهنات Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'somalia', 'AR', 'كود بونص مراهنات Somalia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'somalia', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kenya', 'EN', 'best betting sites Kenya', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kenya', 'EN', 'Kenya bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'kenya', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'zambia', 'EN', 'best betting sites Zambia', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'zambia', 'EN', 'Zambia bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'zambia', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'tanzania', 'EN', 'best betting sites Tanzania', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'tanzania', 'EN', 'Tanzania bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'tanzania', 'SW', 'tovuti bora za kubeti Tanzania', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'tanzania', 'SW', 'msimbo wa bonasi kubeti Tanzania', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'tanzania', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'nigeria', 'EN', 'best betting sites Nigeria', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'nigeria', 'EN', 'Nigeria bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'nigeria', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cameroon', 'FR', 'meilleurs sites paris sportifs Cameroon', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cameroon', 'FR', 'code bonus pari sportif Cameroon', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cameroon', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cote_divoire', 'FR', 'meilleurs sites paris sportifs Cote d''Ivoire', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cote_divoire', 'FR', 'code bonus pari sportif Cote d''Ivoire', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'cote_divoire', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'senegal', 'FR', 'meilleurs sites paris sportifs Senegal', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'senegal', 'FR', 'code bonus pari sportif Senegal', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'senegal', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'benin', 'FR', 'meilleurs sites paris sportifs Benin', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'benin', 'FR', 'code bonus pari sportif Benin', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'benin', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'congo', 'FR', 'meilleurs sites paris sportifs Congo', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'congo', 'FR', 'code bonus pari sportif Congo', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'congo', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'burkina_faso', 'FR', 'meilleurs sites paris sportifs Burkina Faso', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'burkina_faso', 'FR', 'code bonus pari sportif Burkina Faso', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'burkina_faso', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uganda', 'EN', 'best betting sites Uganda', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uganda', 'EN', 'Uganda bookmaker bonus code', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'uganda', 'EN', 'betting affiliate program', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'togo', 'FR', 'meilleurs sites paris sportifs Togo', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'togo', 'FR', 'code bonus pari sportif Togo', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'togo', 'FR', 'programme d''affiliation paris sportifs', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'poland', 'PL', 'najlepsze strony bukmacherskie Poland', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'poland', 'PL', 'kod bonusowy bukmacher Poland', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'poland', 'PL', 'program partnerski bukmacher', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'portugal', 'PT', 'melhores casas de apostas Portugal', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'portugal', 'PT', 'codigo bonus apostas Portugal', 'A', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'portugal', 'PT', 'programa de afiliados apostas', 'B', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'global', 'EN', 'inurl:betting-review "promo code"', 'C', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'global', 'EN', 'site:blogspot.com "betting bonus" review', 'C', true),
((SELECT id FROM public.brands WHERE slug='luckypari'), 'global', 'EN', '"betting affiliate" "contact us" blog', 'C', true)
ON CONFLICT (brand_id, geo, language, keyword) DO NOTHING;
